### ISSUE TITLE
`kusk mock` fails with external-refs

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/kusk-gateway#849]
Example API definition

**openapi.yaml:**
```yaml
openapi: 3.0.0
info:
  title: External Ref
  version: 1.0.0
x-kusk:
  mocking: 
    enabled: true
paths:
  /:
    get:
      summary: Get
      operationId: get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml#/components/schemas/Pet'
```

```
kusk mock -i external-ref.yaml
panic: runtime error: slice bounds out of range [52:47]

goroutine 1 [running]:
github.com/getkin/kin-openapi/openapi3.(*Loader).getResolvedRefPath(0x1400061a000, {0x140004ca400?, 0x1400019b0b0?}, 0x1400019b0b0, 0x140001b4510, 0x140001b5170)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:774 +0xf4
github.com/getkin/kin-openapi/openapi3.(*Loader).resolveSchemaRef(0x1400061a000, 0x140004c7e30?, 0x1400019afc0, 0x140001b4510, {0x1400099eee8, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:714 +0x71c
github.com/getkin/kin-openapi/openapi3.(*Loader).resolveResponseRef(0x1400061a000, 0x106205340?, 0x1400019ae58, 0x140001b4510)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:661 +0x470
github.com/getkin/kin-openapi/openapi3.(*Loader).resolvePathItemRefContinued(0x1060e2820?, 0x14000193890?, 0x1400023c0b0, 0x47?)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:1042 +0x294
github.com/getkin/kin-openapi/openapi3.(*Loader).resolvePathItemRef(0x1400061a000, 0x1400048e000, {0x10721ed18?, 0x1?}, 0x1400023c0b0, 0x140001b4510)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:1021 +0x40c
github.com/getkin/kin-openapi/openapi3.(*Loader).ResolveRefsIn(0x1400061a000, 0x1400048e000, 0x200?)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:227 +0x594
github.com/getkin/kin-openapi/openapi3.(*Loader).loadFromDataWithPathInternal(0x1400061a000, {0x140008f2200, 0x1b0, 0x200}, 0x90?)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:162 +0x144
github.com/getkin/kin-openapi/openapi3.(*Loader).loadFromURIInternal(0x140001ca460?, 0x10632a240?)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:80 +0x58
github.com/getkin/kin-openapi/openapi3.(*Loader).LoadFromURI(...)
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:66
github.com/getkin/kin-openapi/openapi3.(*Loader).LoadFromFile(0x1400061a000, {0x140001ca460, 0x46})
	/home/runner/go/pkg/mod/github.com/getkin/kin-openapi@v0.103.0/openapi3/loader.go:72 +0xe4
github.com/kubeshop/kusk-gateway/pkg/spec.Parser.Parse({{0x1063aa4b0?, 0x1400061a000?}}, {0x140001ca460, 0x46})
	/home/runner/work/kusk-gateway/kusk-gateway/pkg/spec/spec.go:79 +0xfc
github.com/kubeshop/kusk-gateway/cmd/kusk/cmd.glob..func9(0x1072c09a0, {0x105a35b2a?, 0x2?, 0x2?})
	/home/runner/work/kusk-gateway/kusk-gateway/cmd/kusk/cmd/mock.go:190 +0x654
github.com/spf13/cobra.(*Command).execute(0x1072c09a0, {0x140005342c0, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1072bf5a0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/kubeshop/kusk-gateway/cmd/kusk/cmd.Execute()
	/home/runner/work/kusk-gateway/kusk-gateway/cmd/kusk/cmd/root.go:100 +0x28
main.main()
	/home/runner/work/kusk-gateway/kusk-gateway/cmd/kusk/main.go:34 +0x1c
```

**Comment by kylehodgetts** [comment]
Fixed by upgrading get-kin/openapi3 in https://github.com/kubeshop/kusk-gateway/pull/899
Closing
